//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QLQCFEntities : DbContext
    {
       
        public QLQCFEntities()
              : base("name=QLQCFEntities")
        {
        }
      
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbe_ChiTietHoaDon> tbe_ChiTietHoaDon { get; set; }
        public DbSet<tbe_HoaDon> tbe_HoaDon { get; set; }
        public DbSet<tbe_KhachHang> tbe_KhachHang { get; set; }
        public DbSet<tbe_Loai> tbe_Loai { get; set; }
        public DbSet<tbe_NhanVien> tbe_NhanVien { get; set; }
        public DbSet<tbe_TaiKhoan> tbe_TaiKhoan { get; set; }
        public DbSet<tbe_ThucDon> tbe_ThucDon { get; set; }
    
        [EdmFunction("QLQCFEntities", "DoanhThuTheoLoai")]
        public virtual IQueryable<DoanhThuTheoLoai_Result> DoanhThuTheoLoai(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DoanhThuTheoLoai_Result>("[QLQCFEntities].[DoanhThuTheoLoai](@NgayBatDau, @NgayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        [EdmFunction("QLQCFEntities", "TongSoLuongDonTheoThang")]
        public virtual IQueryable<TongSoLuongDonTheoThang_Result> TongSoLuongDonTheoThang(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TongSoLuongDonTheoThang_Result>("[QLQCFEntities].[TongSoLuongDonTheoThang](@NgayBatDau, @NgayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        [EdmFunction("QLQCFEntities", "Top10DoanhThuNhanVien")]
        public virtual IQueryable<Top10DoanhThuNhanVien_Result> Top10DoanhThuNhanVien(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Top10DoanhThuNhanVien_Result>("[QLQCFEntities].[Top10DoanhThuNhanVien](@NgayBatDau, @NgayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        [EdmFunction("QLQCFEntities", "KhachHangMuaNhieuNhat")]
        public virtual IQueryable<KhachHangMuaNhieuNhat_Result> KhachHangMuaNhieuNhat(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<KhachHangMuaNhieuNhat_Result>("[QLQCFEntities].[KhachHangMuaNhieuNhat](@NgayBatDau, @NgayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        [EdmFunction("QLQCFEntities", "SanPhamBanChayNhat")]
        public virtual IQueryable<SanPhamBanChayNhat_Result> SanPhamBanChayNhat(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SanPhamBanChayNhat_Result>("[QLQCFEntities].[SanPhamBanChayNhat](@NgayBatDau, @NgayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        [EdmFunction("QLQCFEntities", "TimKiemNhanVienTheoTen")]
        public virtual IQueryable<TimKiemNhanVienTheoTen_Result> TimKiemNhanVienTheoTen(string tenNhanVien)
        {
            var tenNhanVienParameter = tenNhanVien != null ?
                new ObjectParameter("TenNhanVien", tenNhanVien) :
                new ObjectParameter("TenNhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKiemNhanVienTheoTen_Result>("[QLQCFEntities].[TimKiemNhanVienTheoTen](@TenNhanVien)", tenNhanVienParameter);
        }
    }
}
