//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbe_HoaDon
    {
        public tbe_HoaDon()
        {
            this.tbe_ChiTietHoaDon = new HashSet<tbe_ChiTietHoaDon>();
        }
    
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string MaNhanVien { get; set; }
        public string MaKhachHang { get; set; }
    
        public virtual ICollection<tbe_ChiTietHoaDon> tbe_ChiTietHoaDon { get; set; }
        public virtual tbe_KhachHang tbe_KhachHang { get; set; }
        public virtual tbe_NhanVien tbe_NhanVien { get; set; }
    }
}
