//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbe_ChiTietHoaDon
    {
        public string MaHoaDon { get; set; }
        public string MaThucDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual tbe_HoaDon tbe_HoaDon { get; set; }
        public virtual tbe_ThucDon tbe_ThucDon { get; set; }
    }
}
