//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbe_ThucDon
    {
        public tbe_ThucDon()
        {
            this.tbe_ChiTietHoaDon = new HashSet<tbe_ChiTietHoaDon>();
        }
    
        public string MaThucDon { get; set; }
        public string TenThucDon { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string MaLoai { get; set; }
    
        public virtual ICollection<tbe_ChiTietHoaDon> tbe_ChiTietHoaDon { get; set; }
        public virtual tbe_Loai tbe_Loai { get; set; }
    }
}
