//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbe_NhanVien
    {
        public tbe_NhanVien()
        {
            this.tbe_HoaDon = new HashSet<tbe_HoaDon>();
        }
    
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
    
        public virtual ICollection<tbe_HoaDon> tbe_HoaDon { get; set; }
    }
}
